dashboard/urls.py
from django.urls import path, include

from .views import stakeholders, generate_pdf, generate_pdf_eur
from .views.financial import payments
from .views.stakeholders import index, reports

urlpatterns = [
    path("", index, name="index"),
    path("auth/", include("django.contrib.auth.urls")),
    path("payments/", payments, name="payments"),
    path("reports/", reports, name="reports"),
    path("stakeholders/", stakeholders, name="stakeholders"),
    path("generate_pdf/<int:stakeholder_id>/<int:report_id>/", generate_pdf, name="generate_pdf"),
    path("generate_pdf_eur/<int:stakeholder_id>/<int:report_id>/", generate_pdf_eur, name="generate_pdf_eur"),
]

project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    # path("select2/", include("django_select2.urls")),
    # path("stakeholders/", include("stakeholders.urls")),
    # path("copyright/", include("copyright.urls")),
    path("", include("dashboard.urls")),
]

urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
    urlpatterns.extend(static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))

dashboard/models.py
from django.db import models

from stakeholders.models import Stakeholder
from reports.models import DistributionReport


# Create your models here.
class ViewSplitSong(models.Model):
    unique_id = models.CharField(primary_key=True)
    title = models.CharField(max_length=200)
    quantity = models.IntegerField()
    split = models.FloatField()
    amount = models.FloatField()
    exchange_amount = models.FloatField(null=True, blank=True)
    income = models.FloatField()
    exchange_income = models.FloatField(null=True, blank=True)

    report_title = models.CharField(max_length=200)
    report_start_date = models.DateField()
    distributionreport_id = models.IntegerField()


    stakeholder_id = models.IntegerField()
    # stakeholder = models.ForeignKey(Stakeholder, on_delete=models.DO_NOTHING)
    # distribution_report = models.ForeignKey(DistributionReport, on_delete=models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = "view_split_songs"
    

    @property
    def stakeholder(self):
        return Stakeholder.objects.get(id=self.stakeholder_id)


class Payment(models.Model):
    distributionreport = models.ForeignKey(DistributionReport, on_delete=models.CASCADE)
    stakeholder = models.ForeignKey(Stakeholder, on_delete=models.CASCADE)
    note = models.TextField(null=True, blank=True)

reports/models.py
from django.db import models

# from django.contrib.postgres.fields import ArrayField


# Create your models here.
class ReportAbstractBase(models.Model):
    csv_file = models.FileField(upload_to="reports/datafiles/")
    # Parse CSV to matrix json for after use
    json_data = models.JSONField(null=True, blank=True)
    columns = models.JSONField(null=True, blank=True)
    dtypes = models.JSONField(null=True, blank=True)

    class Meta:
        abstract = True


class DistributionReportPaymentStatus(models.TextChoices):
    done = "done", "Concluído"
    processing = "processing", "Processando"
    opened = "opened", "Aberto"


class DistributionReport(ReportAbstractBase):
    title = models.CharField(max_length=100)
    amount = models.FloatField(null=True, blank=True)
    income = models.FloatField(null=True, blank=True)
    payment_status = models.CharField(
        choices=DistributionReportPaymentStatus.choices,
        default=DistributionReportPaymentStatus.opened,
    )
    start_date = models.DateField(null=True, blank=True)
    end_date = models.DateField(null=True, blank=True)

    def __str__(self):
        return self.title

    def update_amount(self):
        """Update amount field with sum lucro_liquido rows"""
        if not self.amount:
            self.amount = sum(map(lambda x: x["lucro_liquido"], self.json_data))

dashboard/forms.py
from django import forms
from django.utils.functional import lazy

from reports.models import DistributionReport


class DataframeFilter(forms.Form):
    report = forms.ModelChoiceField(queryset=DistributionReport.objects, required=False, label="Relatório")

    columns = forms.MultipleChoiceField(
        label="Colunas", required=False, widget=forms.CheckboxSelectMultiple()
    )

    groupby = forms.MultipleChoiceField(
        label="Agrupar", required=False, widget=forms.CheckboxSelectMultiple()
    )

    def __init__(self, columns: [str], *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.base_fields["columns"].choices = list(map(lambda x: (x, x), columns))

        self.base_fields["groupby"].choices = list(map(lambda x: (x, x), columns))



class StakeholderReportFilter(forms.Form):
    report = forms.ChoiceField(required=False)

    def __init__(self, choices, *args, **kwargs):
        self.base_fields['report'].choices = [("", "Selecione seu relatório")] + choices

        super().__init__(*args, **kwargs)

        

dashboard/views/financial.py
from django.db.models import Count, Sum
from django.shortcuts import render

from dashboard.entries import PaymentAggregation
from dashboard.models import ViewSplitSong
from reports.models import DistributionReport


def payments(request):
    distributionreport = DistributionReport.objects.order_by("-end_date").first()

    qs = ViewSplitSong.objects.filter(distributionreport_id=distributionreport.id)

    payments = sorted(
        list(
            map(
                lambda kwargs: PaymentAggregation(distributionreport_id=distributionreport.id, **kwargs),
                (
                    qs.values("stakeholder_id")
                    .order_by("stakeholder_id")
                    .annotate(
                        total_shares=Count("unique_id"),
                        total_quantity=Sum("quantity"),
                        total_earnings=Sum("exchange_income"),
                    )
                ),
            )
        ),
        key=lambda x: -x.total_earnings,
    )

    context = {"distributionreport": distributionreport, "payments": payments}

    return render(
        request, template_name="dashboard/financial/payments.html", context=context
    )


# def pay(request, stakeholder_id, distributionreport_id):

dashboard/views/stakeholders.py
import json

from django.db.models import Count
from django.shortcuts import render
from django.contrib.auth.decorators import login_required

from reports.models import DistributionReport, DistributionReportPaymentStatus

# from reports.split.models import SplitLine
from dashboard.dbutils import view_reports
from dashboard.models import ViewSplitSong
from dashboard.forms import StakeholderReportFilter


@login_required
def index(request):
    stakeholder = request.user.stakeholder_set.first()
    report = DistributionReport.objects.last()

    qs = ViewSplitSong.objects.filter(
        stakeholder_id=stakeholder.id, distributionreport_id=report.id
    )

    split_songs = qs.order_by("-income", "-title")
    reports = view_reports(stakeholder, "2020-01-01")

    labels = list(map(lambda x: x["title"], reports))
    values = list(map(lambda x: float(x["exchange_income"]), reports))

    ctx = {
        "report": report,
        "split_songs": split_songs[:5],
        "chart": {"labels": json.dumps(labels), "values": json.dumps(values)},
    }

    if report.payment_status == DistributionReportPaymentStatus.opened:
        ctx.update(
            {
                "next_payment": {
                    "currency": "EUR",
                    "value": round(sum(list(map(lambda x: x.income, split_songs))), 2),
                }
            }
        )
    elif report.payment_status == DistributionReportPaymentStatus.processing:
        ctx.update(
            {
                "next_payment": {
                    "currency": "PREV",
                    "value": round(
                        sum(list(map(lambda x: x.exchange_income, split_songs))), 2
                    ),
                }
            }
        )
    elif report.payment_status == DistributionReportPaymentStatus.done:
        ctx.update(
            {
                "next_payment": {
                    "currency": "BRL",
                    "value": round(
                        sum(list(map(lambda x: x.exchange_income, split_songs))), 2
                    ),
                }
            }
        )

    return render(request, "dashboard/stakeholders/index.html", ctx)


@login_required
def reports(request):
    stakeholder = request.user.stakeholder_set.first()

    reports = (
        ViewSplitSong.objects.filter(stakeholder_id=stakeholder.id)
        .values("distributionreport_id", "report_title", "report_start_date")
        .annotate(count=Count("report_title"))
        .order_by("-report_start_date")
    )

    form = StakeholderReportFilter(
        data=request.GET,
        choices=list(
            map(lambda x: (x["distributionreport_id"], x["report_title"]), reports)
        ),
    )

    ctx = {"filter": form, "reports": reports, "split_songs": []}

    if form.is_valid() and form.cleaned_data["report"]:
        split_songs = ViewSplitSong.objects.filter(
            stakeholder_id=stakeholder.id,
            distributionreport_id=form.cleaned_data["report"],
        ).order_by("title")
        ctx.update({"split_songs": split_songs})

    return render(request, "dashboard/stakeholders/reports.html", ctx)

dashboard/templates/dashboard/financial/payments.html
{% extends 'dashboard/stakeholders/base.html' %}
{% load dashboard %}

{% block head_title %}Gestão360º | Pagamentos{% endblock %}

{% block content %}
<!-- Page Heading -->
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Pagamentos</h1>
</div>

<!-- Content Row -->
<div class="row">
    <div class="col-12">
        <div class="card shadow mb-4">
            <!-- Card Header - Dropdown -->
            <div
                class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                <h6 class="m-0 font-weight-bold text-primary">Relatório: {{ distributionreport.title }}</h6>
            </div>
            <!-- Card Body -->
            <div class="card-body">
                <p>{{ distributionreport.start_date }} - {{ distributionreport.end_date }}</p>
                <p>{{ distributionreport.income }}</p>
                <p>{{ distributionreport.get_payment_status_display }}</p>
            </div>
        </div>
    </div>
    <div class="col-12">
        <div class="card shadow mb-4">
            <!-- Card Header - Dropdown -->
            {% comment %} <div
                class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                <h6 class="m-0 font-weight-bold text-primary">Top 5: {{ report.title }}</h6>
            </div> {% endcomment %}
            <!-- Card Body -->
            <div class="card-body">
                <div class="pt-2 pb-2">
                    <table class="table table-borderless table-hover table-xs">
                        <thead>
                          <tr>
                            <th scope="col" class="text-xs">#</th>
                            <th scope="col" class="text-xs">Recebedor</th>
                            <th scope="col" class="text-xs">Participações</th>
                            <th scope="col" class="text-xs">Quantidade</th>
                            <th scope="col" class="text-xs">Valor a pagar</th>
                            <th scope="col" class="text-xs">Ações</th>
                          </tr>
                        </thead>
                        <tbody>
                            {% for payment in payments %}
                            <tr>
                                <th scope="row" class="text-xs">{{ forloop.counter }}</th>
                                <td class="text-xs">{{ payment.stakeholder.full_name }}</td>
                                <td class="text-xs">{{ payment.total_shares }}</td>
                                <td class="text-xs">{{ payment.total_quantity|display_numbers }}</td>
                                <td class="text-xs">{{ payment.total_earnings|display_numbers }}</td>
                                <td class="text-xs">
                                    <div>
                                        <a href="{% url 'generate_pdf' payment.stakeholder.id distributionreport.id %}" class="btn btn-sm{% if payment.paid %} btn-success{% else %} btn-secondary{% endif %}" target="_blank">
                                            <span class="fa fa-print"></span> Recibo
                                        </a>
                                    </div>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
                {% comment %} <div class="mt-4 text-center small">
                    <span class="mr-2">
                        <i class="fas fa-circle text-primary"></i> Direct
                    </span>
                    <span class="mr-2">
                        <i class="fas fa-circle text-success"></i> Social
                    </span>
                    <span class="mr-2">
                        <i class="fas fa-circle text-info"></i> Referral
                    </span>
                </div> {% endcomment %}
            </div>
        </div>
    </div>
</div>
{% endblock %}